// <auto-generated />
namespace IstanbulUni.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lastactivitycreatr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastactivitycreatr));
        
        string IMigrationMetadata.Id
        {
            get { return "202207250703362_lastactivity-creatr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
